Parameters:
  ECRName:
    Type: String
    Description: Name of the ECR repository to create
  Mutability:
    Type: String
    Description: Image tag mutability. Set to MUTABLE to allow tags to be overridden or IMMUTABLE to prevent it
    AllowedValues:
      - MUTABLE
      - IMMUTABLE

Resources:
  ECR:
    Type: AWS::ECR::Repository
    Properties:
      EncryptionConfiguration:
        EncryptionType: KMS
      ImageTagMutability: !Ref Mutability
      RepositoryName: !Ref ECRName
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Only keep 2 untagged images",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "imageCountMoreThan",
                  "countNumber": 2
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  RepositoryURI:
    Value: !GetAtt ECR.RepositoryUri
    Description: URI of created repository