Parameters:
  KMSKeyAliasName:
    Type: String
    Description: Alias for KMS key
    Default: alias/encrypted-bucket-example
    AllowedPattern: alias/[a-zA-Z0-9/_-]+

Resources:
  EncryptedBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: !Ref KMSKey
              SSEAlgorithm: 'aws:kms'
            BucketKeyEnabled: true
    DependsOn: KMSKeyAlias

  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Version: '2012-10-17'
        Id: !Sub ${AWS::StackName}-key-policy
        Statement:
        - Sid: AllowRootAdministration
          Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
          Action: kms:*
          Resource: '*'
        - Sid: AllowKeyUsage
          Effect: Allow
          Principal:
            AWS: '*'
          Action:
            - kms:DescribeKey
            - kms:Encrypt
            - kms:Decrypt
            - kms:ReEncrypt*
            - kms:GenerateDataKey*
            - kms:CreateGrant
            - kms:ListGrants
          Resource: '*'
          Condition:
            StringEquals:
              'kms:ViaService':
                - !Sub s3.${AWS::Region}.amazonaws.com
              'kms:CallerAccount': !Sub ${AWS::AccountId}
  
  KMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Ref KMSKeyAliasName
      TargetKeyId: !Ref KMSKey